name: Run Notebooks and App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-notebooks-and-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        poetry install --no-root

    - name: Run Notebooks
      run: |
        conda run -n .conda jupyter nbconvert --to notebook --execute notebooks/*.ipynb

    - name: Run App
      run: |
        conda run -n .conda python src/app.py
